### ISSUE TITLE
crash with "meteor clicent"

### ISSUE THREAD

**Issue by Blalala6868** [lovexyn0827/Permanent-Chatlogs#2]
Crash Report: https://mclo.gs/5PJRm2U

**Comment by lovexyn0827** [comment]
The cause is obvious, but currently i have no idea on how to fix it gracefully ...

**Comment by lovexyn0827** [comment]
Fixed in [0.2.2+build20240130](https://modrinth.com/mod/permanent-chatlogs/version/JY3HGjn3)
