### ISSUE TITLE
Searching is not working how it's supposed to work

### ISSUE THREAD

**Issue by Andziaa** [lovexyn0827/Permanent-Chatlogs#3]
Searching for anything except Save Name is just horrible.

https://youtu.be/LjURy4hE3wE

On the YouTube video, I'm trying to find something from 2024-03-06, and it shows me a bunch of stuff from February or even January! Then in the next step I'm trying to find something from this date, and it shows up, just because I wrote "Craftplay" save name.

I have one idea to fix this issue: Since the date and the time are together, let's try to cut them from each other to let user search only for a particular date.

**Comment by lovexyn0827** [comment]
Actually, only numerical inputs like 20240306, 202403 or 2024 are supported now, and I have to admit that it wasn't a good idea, so I am going to change it soon.

Sorry for the inconvenience.

**Comment by lovexyn0827** [comment]
[](https://modrinth.com/mod/permanent-chatlogs/version/gZaCdWW0)

Uploaded a new version that supports date input like 2024-03-07 (hopefully any delimiter except numbers are supported). If it works well, I will add this change to the next release.
