### ISSUE TITLE
Crashing when disconnecting from server

### ISSUE THREAD

**Issue by GraySquyd** [lovexyn0827/Permanent-Chatlogs#4]
Crash Report: https://mclo.gs/rFb90hF

**Comment by lovexyn0827** [comment]
Unable to reproduce. Could you please offer more information on when the crash happens? (MC version, etc.)

**Comment by lovexyn0827** [comment]
Successfully located the cause of the bug, however, it is not trivial to fix it gracefully...

**Comment by lovexyn0827** [comment]
> It looks like I mistyped the autosave timing so it was doing it every 10s, so the file had a high chance of being in use.

Actually, autosaved chat logs are only used to recover data after the session terimates abnormally (e.g. when the game crashes), and is simply ignored if we exit the game properly. Therefore, we can theoretically set the interval between autosaves to any reasonable value, as long as it doesn't cause notable performance drop.
