### ISSUE TITLE
port to 1.21

### ISSUE THREAD

**Issue by E0x72-21** [lovexyn0827/Permanent-Chatlogs#8]
please update the mod to 1.21

**Comment by lovexyn0827** [comment]
Actually versions for MC1.20.6 can ce directly installed on MC1.21 without any modification, but I am uploading a separate jar to avoid confusion.

[https://modrinth.com/mod/permanent-chatlogs/version/0.2.3-build20240714](https://modrinth.com/mod/permanent-chatlogs/version/0.2.3-build20240714)
