### ISSUE TITLE
【新功能建议】

### ISSUE THREAD

**Issue by MNWZ211** [lovexyn0827/Permanent-Chatlogs#9]
![e9ad75fa06269cf81f235f659a4fa2c1](https://github.com/user-attachments/assets/7b7226c3-6713-492e-b0f0-4bfe533a05a2)

1. 如上图，在添加了 [Realms按钮移除](https://www.mcmod.cn/class/12228.html) 模组后，按钮位置并未移动，建议自适应；
2. 将单人和多人的聊天记录单独分为两个模块，方便查找；
3. 筛选提供下拉菜单建议，如存同一存档名称（多次记录）、仅存在的日期范围；
4. 支持删除单次的聊天记录，并支持将其导出如 txt 文本文档的功能；
5. 添加返回主菜单的按钮，同时保留Esc快捷键的退出功能。
6. 设置文本支持中文；

望作者酌情采纳！

**Comment by lovexyn0827** [comment]
感谢反馈！

> 按钮位置并未移动，建议自适应

当时没仔细了解这种自适应有没有一个相对简单的办法来实现，如果可以的话会试一试

> 筛选提供下拉菜单建议，如存同一存档名称（多次记录）、仅存在的日期范围

印象中原版MC中没有下拉菜单这一个GUI组件，需要自己从头去写或者使用原版中不大理想的替代品，等解决完目前积攒的问题后会再试着写一下。不过添加一个Tab补全应该还是可以的。

> 支持删除单次的聊天记录，并支持将其导出如 txt 文本文档的功能

这些功能其实现在正好在做，此外还会计划支持批量删除以及导出到HTML或Markdown这样的格式。

**Comment by lovexyn0827** [comment]
做的有点点慢这些天

[permanent-chat-logs-0.3.0-build20241011.jar.zip](https://github.com/user-attachments/files/17339117/permanent-chat-logs-0.3.0-build20241011.jar.zip)

> 如上图，在添加了 [Realms按钮移除](https://www.mcmod.cn/class/12228.html) 模组后，按钮位置并未移动，建议自适应；

因为原版限制，这一需求似乎没有一个可靠的实现方式。

> 将单人和多人的聊天记录单独分为两个模块，方便查找；

现在基本上已经做好了一个框架了，然而原先的聊天记录该如何归类还不确定，希望可以给出一些建议。

> 筛选提供下拉菜单建议，如存同一存档名称（多次记录）、仅存在的日期范围；

在存档名称中添加了这样的一个提示词和Tab补全，按符合程度和出现次数决定优先级。日期范围实际上也可以省略具体的月或日。

![image](https://github.com/user-attachments/assets/39e1fa00-c668-4247-8ac9-ebb840877413)

> 支持删除单次的聊天记录，并支持将其导出如 txt 文本文档的功能；
> 添加返回主菜单的按钮，同时保留Esc快捷键的退出功能。

现在大致已经做好了，导出聊天记录这块之后的话可能会添加一些格式自定义选项。（图为导出的HTML）

![image](https://github.com/user-attachments/assets/05f1707f-1eab-4e15-a2a6-cb2c4537ae3d)

> 设置文本支持中文；

因为文本长度限制，这里没有翻译选项的名称，但是参考Tweakeroo添加了一个提示框。

![image](https://github.com/user-attachments/assets/9bb804e1-8314-4613-98c2-41ccbac2b9a1)

![image](https://github.com/user-attachments/assets/6db67ad4-d6ee-4cc7-91a5-0913e07609a2)

**Comment by lovexyn0827** [comment]
新版本已发布

https://modrinth.com/mod/permanent-chatlogs/version/0.3.0-build20241012

**Comment by MNWZ211** [comment]
> 新版本已发布
> 
> https://modrinth.com/mod/permanent-chatlogs/version/0.3.0-build20241012


能否支持其他版本

**Comment by lovexyn0827** [comment]
> 能否支持其他版本

按原来的设想，等时间宽裕了会支持到1.16.4到1.21.1。
